# Generated by Django 4.0 on 2022-01-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('is_home', models.BooleanField(default=False)),
            ],
        ),
    ]
